name: myskin_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  camera: ^0.11.0+2
  file_picker: ^9.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  image_picker: ^1.1.2
  intl: ^0.18.1
  json_annotation: ^4.9.0
  modal_progress_hud_nsn: ^0.5.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"

  web: false
