name: myskin_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0

flutter:
  uses-material-design: 
  assets:
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
  
